### PR TITLE
docs(README): update README to reference MDN docs

### PR DESCRIPTION
**Pull request by 100stacks**
# Submitting PR:

* reference MDN Guide on cross-browser testing
* reference MDN automated testing tutorial
* Additionally, the wiki is referencing a `Mozilla/Sauce Labs extended trial offer`, which is no longer available.

## Thank you Mozilla for all you do for the global community!!! 🎉

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
Thanks for the contribution, @100stacks . I've removed the references to the sauce labs trial from the Wiki too, good call.

Your update here looks mostly fine; the only thing I'd like to see changed is the way you reference the MDN Web Docs pages. For a start, the title has changed, and the grammar could do with a little tweak.  Can you change both of the references to use  the following format?

```
[Guide to Cross Browser Testing](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing) on MDN Web Docs
```

?

Thanks again.

**Comment by 100stacks** [comment]
Sounds great @chrisdavidmills!  Your recommendations definitely flow better.

I'll push up the changes.

Thanks!

**Comment by 100stacks** [comment]
Hi @chrisdavidmills, I worked on the wording for the sections.

Also, the new section titles are a little longer.  I can keep the heading size as is, or use a `<h2>` or `<h3>` if you prefer.

Thanks again 👍

**Comment by chrisdavidmills** [comment]
@100stacks thanks James! Yeah, the two sub-headings should really be `<h2>`s, to create a proper heading hierarchy. Can you change them? after that I'll merge. Cheers!

**Comment by 100stacks** [comment]
Ok cool, @chrisdavidmills! I made the two sub-headings `<h2>` ...anything else please let me know.

Appreciate you taking the time!!!

**Comment by chrisdavidmills** [comment]
Great! Merged.

Thanks for the contribution; we really appreciate it.

**Pull request merged**
